# Generated by Django 4.2.30 on 2026-04-15 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(default='Gameserver Panel', max_length=128)),
                ('public_base_url', models.CharField(blank=True, help_text='Veřejná URL panelu, např. https://panel.example.com', max_length=256)),
                ('timezone', models.CharField(default='Europe/Prague', max_length=64)),
                ('default_language', models.CharField(default='cs', max_length=8)),
                ('default_startup_timeout', models.IntegerField(default=60, help_text='Výchozí timeout startu serveru (sekundy)')),
                ('default_shutdown_timeout', models.IntegerField(default=30, help_text='Výchozí timeout vypnutí serveru (sekundy)')),
                ('raw_metrics_retention_days', models.IntegerField(default=7, help_text='Retence raw metrik (dny)')),
                ('minute_metrics_retention_days', models.IntegerField(default=60, help_text='Retence minutových metrik (dny)')),
                ('console_retention_days', models.IntegerField(default=14, help_text='Retence konzole logů (dny)')),
                ('runtime_poll_console_ms', models.IntegerField(default=500, help_text='Interval tailu konzole (ms)')),
                ('runtime_poll_metrics_seconds', models.IntegerField(default=12, help_text='Interval sběru metrik (sekundy)')),
                ('runtime_poll_watchdog_seconds', models.IntegerField(default=15, help_text='Interval watchdogu (sekundy)')),
                ('alert_cooldown_minutes', models.IntegerField(default=15, help_text='Minimální pauza mezi stejnými alerty (minuty)')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='BootstrapState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('schema_version', models.CharField(default='1.0', max_length=32)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bootstrap State',
            },
        ),
    ]
