# Generated by Django 4.2.30 on 2026-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, help_text='Povolit odesílání emailů'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_from_address',
            field=models.EmailField(blank=True, help_text='Odesílací adresa, např. panel@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server, např. smtp.gmail.com', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Heslo k SMTP (uloženo plaintext)', max_length=256),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.IntegerField(default=587, help_text='SMTP port (587 = TLS, 465 = SSL, 25 = plain)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Použít SSL (port 465)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Použít STARTTLS (port 587)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_username',
            field=models.CharField(blank=True, help_text='Přihlašovací jméno k SMTP', max_length=256),
        ),
    ]
