# Generated by Django 4.2.30 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metrichour',
            new_name='metrics_met_server__fb97a0_idx',
            old_name='metrics_hour_server_ts',
        ),
        migrations.RenameIndex(
            model_name='metricminute',
            new_name='metrics_met_server__58129c_idx',
            old_name='metrics_minute_server_ts',
        ),
        migrations.RenameIndex(
            model_name='metricsample',
            new_name='metrics_met_server__7cbc96_idx',
            old_name='metrics_sample_server_ts',
        ),
        migrations.AlterField(
            model_name='metrichour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metricminute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metricsample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
