# Generated by Django 4.2.30 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertfire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='channel',
            field=models.CharField(choices=[('webhook', 'Webhook (Discord/Slack/Teams)')], default='webhook', max_length=16),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='condition_type',
            field=models.CharField(choices=[('status_change', 'Změna stavu serveru'), ('cpu_threshold', 'CPU přes limit'), ('ram_threshold', 'RAM přes limit'), ('no_players', 'Žádní hráči'), ('log_pattern', 'Pattern v logu')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='message_template',
            field=models.TextField(default='🚨 [{server_name}] Alert: {condition} – {details}', help_text='Dostupné proměnné: {server_name}, {status}, {value}, {condition}'),
        ),
    ]
