# Generated by Django 4.2.30 on 2026-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alertfire_id_alter_alertrule_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Cílová emailová adresa (pro kanál Email)', max_length=254),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='channel',
            field=models.CharField(choices=[('webhook', 'Webhook (Discord/Slack/Teams)'), ('email', 'Email')], default='webhook', max_length=16),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
    ]
