# Generated by Django 4.2.30 on 2026-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playersession',
            new_name='servers_pla_server__75a11f_idx',
            old_name='ps_server_joined_idx',
        ),
        migrations.RenameIndex(
            model_name='playersession',
            new_name='servers_pla_player__61b371_idx',
            old_name='ps_player_idx',
        ),
        migrations.AlterField(
            model_name='playersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='server',
            name='game_type',
            field=models.CharField(choices=[('minecraft_java', 'Minecraft Java'), ('minecraft_bedrock', 'Minecraft Bedrock'), ('terraria', 'Terraria'), ('factorio', 'Factorio'), ('other', 'Ostatní')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('STARTING', 'Startuje'), ('ONLINE', 'Online'), ('STOPPING', 'Zastavuje se'), ('CRASHED', 'Crashed'), ('UNKNOWN', 'Neznámý')], default='OFFLINE', max_length=16),
        ),
        migrations.AlterField(
            model_name='serverprocessstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serverprocessstate',
            name='status',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('STARTING', 'Startuje'), ('ONLINE', 'Online'), ('STOPPING', 'Zastavuje se'), ('CRASHED', 'Crashed'), ('UNKNOWN', 'Neznámý')], default='OFFLINE', max_length=16),
        ),
    ]
