# Generated by Django 4.2.30 on 2026-04-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_rename_ps_server_joined_idx_servers_pla_server__75a11f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('jar_file', models.CharField(default='server.jar', help_text='Název jar souboru v working_directory', max_length=256)),
                ('heap_min_mb', models.IntegerField(default=512, help_text='Xms v MB')),
                ('heap_max_mb', models.IntegerField(default=2048, help_text='Xmx v MB')),
                ('jvm_flags', models.TextField(blank=True, help_text='Další JVM flagy, každý na novém řádku')),
                ('extra_args', models.TextField(blank=True, help_text='Argumenty za jar souborem (např. --nogui)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_profiles', to='servers.server')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('server', 'name')},
            },
        ),
    ]
