# Generated by Django 4.2.30 on 2026-04-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_startprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRestart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Volitelný popis, např. 'Noční restart'", max_length=64)),
                ('cron_expression', models.CharField(help_text="5-polní cron výraz, např. '0 4 * * *'", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('warn_minutes', models.IntegerField(default=5, help_text='Kolik minut předem varovat hráče (0 = bez varování)')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_restarts', to='servers.server')),
            ],
            options={
                'ordering': ['cron_expression'],
            },
        ),
    ]
