# Generated by Django 4.2.30 on 2026-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_scheduled_restart'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='backup_keep_count',
            field=models.IntegerField(default=7, help_text='Počet záloh k uchování (rotace)'),
        ),
    ]
