# Generated by Django 4.2.30 on 2026-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_backup_keep_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='log_file_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='server',
            name='start_command',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
