# Generated by Django 4.2.30 on 2026-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_start_command_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='startprofile',
            name='java_path',
            field=models.CharField(blank=True, default='', help_text="Cesta k java.exe / java. Prázdné = použít 'java' z PATH.", max_length=512),
        ),
    ]
