# Generated by Django 4.2.30 on 2026-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_java_path_startprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tmux_session_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
