# Generated by Django 4.2.30 on 2026-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_server__571614_idx',
            old_name='audit_server_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
